import { ProductTier } from "@/types/subscriptions";

export const SUBSCRIPTION_TIERS: ProductTier[] = [
  {
    name: "Basic",
    id: "tier-basic",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "$9",
    description: "Perfect for casual creators and hobbyists.",
    features: [
      "100 image credits per month",
      "Standard resolution (1024x1024)",
      "5 artistic styles",
      "No watermarks",
      "Commercial use license",
      "Email support",
    ],
    featured: false,
    discountCode: "",
  },
  {
    name: "Pro",
    id: "tier-pro",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "$29",
    description: "Ideal for serious creators and small businesses.",
    features: [
      "500 image credits per month",
      "High resolution (2048x2048)",
      "20+ artistic styles",
      "Priority generation speed",
      "Commercial use license",
      "Priority email support",
      "API access",
    ],
    featured: true,
    discountCode: "",
  },
  {
    name: "Enterprise",
    id: "tier-enterprise",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "$99",
    description: "For agencies and large-scale production.",
    features: [
      "2000 image credits per month",
      "4K resolution (4096x4096)",
      "All artistic styles",
      "Fastest generation speed",
      "Commercial use license",
      "Dedicated account manager",
      "Full API access",
      "Custom fine-tuning",
    ],
    featured: false,
    discountCode: "",
  },
];

export const CREDITS_TIERS: ProductTier[] = [
  {
    name: "Starter Pack",
    id: "tier-50-credits",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "$5",
    description: "Perfect for trying out and small projects.",
    creditAmount: 50,
    features: [
      "50 image credits",
      "Standard resolution (1024x1024)",
      "10 artistic styles",
      "No expiration date",
      "Commercial use license",
    ],
    featured: false,
    discountCode: "",
  },
  {
    name: "Creator Pack",
    id: "tier-200-credits",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "$19",
    description: "Great for regular creators and designers.",
    creditAmount: 200,
    features: [
      "200 image credits",
      "High resolution (2048x2048)",
      "All artistic styles",
      "No expiration date",
      "Commercial use license",
      "Priority support",
    ],
    featured: true,
    discountCode: "",
  },
  {
    name: "Pro Pack",
    id: "tier-1000-credits",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "$79",
    description: "Best value for heavy users and agencies.",
    creditAmount: 1000,
    features: [
      "1000 image credits",
      "4K resolution (4096x4096)",
      "All artistic styles",
      "No expiration date",
      "Commercial use license",
      "Priority generation speed",
      "Premium support",
    ],
    featured: false,
    discountCode: "",
  },
];
